# -*- coding: utf-8 -*-
"""BiStartX Staj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VUBHrstyu-QI2ucD-WKKR8Oj29DopXnr
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

file_path = '/content/titanic3.xls'
titanic_df = pd.read_excel(file_path)

display(titanic_df.head())
display(titanic_df.info())

titanic_df = titanic_df.copy()

display(titanic_df.isnull().sum())

titanic_df['age'].fillna(titanic_df['age'].median(), inplace=True)
titanic_df['fare'].fillna(titanic_df['fare'].median(), inplace=True)
titanic_df['embarked'].fillna(titanic_df['embarked'].mode()[0], inplace=True)

drop_columns = ['cabin', 'boat', 'body', 'home.dest']
existing_columns = [col for col in drop_columns if col in titanic_df.columns]
titanic_df.drop(columns=existing_columns, inplace=True)

display(titanic_df.isnull().sum())

plt.figure(figsize=(10, 5))
sns.countplot(data=titanic_df, x='survived')
plt.title('Survival Distribution')
plt.xlabel('Survived')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.histplot(data=titanic_df, x='age', bins=30, kde=True)
plt.title('Age Distrubition')
plt.xlabel('Age')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.barplot(data=titanic_df, x='pclass', y='survived')
plt.title('Survival Rate by Passenger Class')
plt.xlabel('Passenger Class')
plt.ylabel('Survival Rate (%)')
plt.show()

plt.figure(figsize=(10, 5))
sns.boxplot(data=titanic_df, x='survived', y='age')
plt.title('Age Distribution of Survivors and Non-Survivors')
plt.xlabel('Survived')
plt.ylabel('Age')
plt.show()

plt.figure(figsize=(10, 5))
sns.countplot(data=titanic_df, x='sex', hue='survived')
plt.title('Survival by Gender')
plt.xlabel('Sex')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 5))
sns.countplot(data=titanic_df, x='embarked', hue='survived')
plt.title('Survival by Embarkation Point')
plt.xlabel('Embarkation Point')
plt.ylabel('Count')
plt.show()