# -*- coding: utf-8 -*-
"""BiStartXinternship2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14vMZRlAtFOUzkcRK3pYxo5t1FAvnQbVa
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/SuperStore.csv')
df.head()

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

df['YearMonth'] = df['Order Date'].dt.to_period('M')

monthly_revenue = df.groupby('YearMonth')['Sales'].sum().reset_index()
monthly_revenue.columns = ['Month', 'Revenue']
monthly_revenue['Revenue'] = pd.to_numeric(monthly_revenue['Revenue'], errors='coerce')
monthly_revenue['Month'] = monthly_revenue['Month'].astype(str)

monthly_avg_order = df.groupby(['YearMonth', 'Order ID'])['Sales'].sum().groupby('YearMonth').mean().reset_index()
monthly_avg_order.columns = ['Month', 'Avg_Order_Size']
monthly_avg_order['Avg_Order_Size'] = pd.to_numeric(monthly_avg_order['Avg_Order_Size'], errors='coerce')
monthly_avg_order['Month'] = monthly_avg_order['Month'].astype(str)

plt.figure(figsize=(14, 6))
sns.lineplot(data=monthly_revenue, x='Month', y='Revenue', label='Monthly Revenue')
sns.lineplot(data=monthly_avg_order, x='Month', y='Avg_Order_Size', label='Avg Order Size')
plt.title("Monthly Sales Revenue and Average Order Size")
plt.xlabel("Month")
plt.ylabel("Cost (USD)")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

df['YearMonth'] = df['Order Date'].dt.to_period('M')
df['YearMonth'] = df['YearMonth'].astype(str)

monthly_category_sales = df.groupby(['YearMonth', 'Category'])['Sales'].sum().reset_index()

plt.figure(figsize=(14, 6))
sns.lineplot(data=monthly_category_sales, x='YearMonth', y='Sales', hue='Category')
plt.title("Category Based Monthly Sales Trends")
plt.xlabel("Month")
plt.ylabel("Sales (USD)")
plt.xticks(rotation=45)
plt.legend(title="Category")
plt.tight_layout()
plt.show()

state_sales = df.groupby('State')['Sales'].sum().sort_values(ascending=False).head(10).reset_index()

plt.figure(figsize=(12, 6))
sns.barplot(data=state_sales, x='Sales', y='State', palette='viridis')
plt.title("Top 10 Highest Sales States")
plt.xlabel("Total Sales (USD)")
plt.ylabel("State")
plt.tight_layout()
plt.show()

monthly_segment_sales = df.groupby(['YearMonth', 'Segment'])['Sales'].sum().reset_index()

plt.figure(figsize=(14, 6))
sns.lineplot(data=monthly_segment_sales, x='YearMonth', y='Sales', hue='Segment')
plt.title("Monthly Sales Trends by Customer Segment")
plt.xlabel("Month")
plt.ylabel("Sales (USD)")
plt.xticks(rotation=45)
plt.legend(title="Segment")
plt.tight_layout()
plt.show()