# -*- coding: utf-8 -*-
"""BiStartXinternship3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HMa8BAwq2U5_unvBRwqSC-STzxKbWpHD
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/weatherHistory.csv')

df['Formatted Date'] = pd.to_datetime(df['Formatted Date'], utc=True)

df['Year'] = df['Formatted Date'].dt.year
df['Month'] = df['Formatted Date'].dt.month

def get_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:
        return 'Autumn'

df['Season'] = df['Month'].apply(get_season)

seasonal_avg = df.groupby('Season')['Temperature (C)'].mean().reindex(['Winter', 'Spring', 'Summer', 'Autumn'])

seasonal_df = seasonal_avg.reset_index()
seasonal_df.columns = ['Season', 'AvgTemp']

plt.figure(figsize=(8, 5))
sns.barplot(data=seasonal_df, x='Season', y='AvgTemp', hue='Season', palette='coolwarm', legend=False)
plt.title('Average Temperature by Season')
plt.xlabel('Season')
plt.ylabel('Temperature (°C)')
plt.grid(axis='y')
plt.tight_layout()
plt.show()