# -*- coding: utf-8 -*-
"""BiStartXinternship4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WR4eq7XaAiaUqgIj5bfNREbShOMd6GJ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import silhouette_score

df = pd.read_csv('/content/Mall_Customers.csv')
df.head()

df.info()
df.describe()

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(df['Age'], kde=True)
plt.title('Age Distribution')

plt.subplot(1, 1, 1)
sns.histplot(df['Annual Income (k$)'], kde=True)
plt.title('Annual Income Distribution')

plt.subplot(1, 1, 1)
sns.histplot(df['Spending Score (1-100)'], kde=True)
plt.title('Spending Score Distrubution')

plt.tight_layout()
plt.show()

features = df[['Age', 'Annual Income (k$)', 'Spending Score (1-100)']]
scaler = MinMaxScaler()
scaled_features = scaler.fit_transform(features)

inertia = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(scaled_features)
    inertia.append(kmeans.inertia_)

plt.plot(range(1, 11), inertia, marker='o')
plt.xlabel('Cluster Number')
plt.ylabel('Inertia')
plt.title('Elbow Method')
plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)
df['Segment'] = kmeans.fit_predict(scaled_features)

sns.pairplot(df, hue='Segment', vars=['Age', 'Annual Income (k$)', 'Spending Score (1-100)'], palette='tab10')
plt.suptitle("Customer Segments", y=1.02)
plt.show()